# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32b3be1339cd304268ecd37e6314edb568ca0fe4048835a2cb066e6c7c1b90b0364d38a73ba3d3c7538bd8bcd674b66df943d196c98e406624e54b6516005ba4

test:
  secret_key_base: feccc003849eebd20eabeebf39371950149aac61d3db1836b4508609431d1557c1d34f0ebe12b3194f4e837d9ecd1b41d40437b1566d0f0f2bdf6da9ab38fbb3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
